name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  wait-for-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for .NET workflow
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  create-release:
    needs: wait-for-dotnet
    runs-on: ubuntu-latest
    steps:
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
      - name: Mark release complete
        run: echo "Release created successfully"
